<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DoB_Day</name>
   <tag></tag>
   <elementGuidId>aaaf1598-faa5-4c85-ba0f-78d4a727e360</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//Select[@id=&quot;days&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
